aiarena/api/urls.py
from aiarena.api import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'bots', views.BotViewSet, basename='bot')
router.register(r'maps', views.MapViewSet, basename='map')
router.register(r'matches', views.MatchViewSet, basename='match')
router.register(r'participants', views.ParticipantViewSet, basename='participant')
router.register(r'results', views.ResultViewSet, basename='result')
urlpatterns = router.urls

aiarena/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView
import private_storage.urls

from aiarena.core import views as core_views

urlpatterns = [
    path('private-media/bots/<int:pk>/bot_zip', core_views.BotZipDownloadView.as_view()),
    url('^private-media/', include(private_storage.urls)),  # required for django admin
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url('rules', TemplateView.as_view(template_name='rules.html'), name='rules'),
    path('api/', include('aiarena.api.urls')),
    path('ranking/', core_views.Ranking.as_view(), name='ranking'),
    path('results/', core_views.Results.as_view(), name='results'),
    path('bots/', core_views.BotList.as_view(), name='bots'),
    path('bots/<int:pk>/', core_views.BotDetail.as_view(), name='bot'),
    path('authors/', core_views.AuthorList.as_view(), name='authors'),
    path('authors/<int:pk>/', core_views.AuthorDetail.as_view(), name='author'),
    path('botupload/', core_views.BotUpload.as_view(), name='botupload'),
    url('avatar/', include('avatar.urls')),
    path('profile/', core_views.UserProfile.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # https://stackoverflow.com/questions/5517950/django-media-url-and-media-root

aiarena/core/models.py
import logging

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse
from private_storage.fields import PrivateFileField

from aiarena.core.utils import calculate_md5
from aiarena.settings import ELO_START_VALUE

logger = logging.getLogger(__name__)


class User(AbstractUser):
    email = models.EmailField(unique=True)
    serviceaccount = models.BooleanField(default=0)


def bot_zip_upload_to(instance, filename):
    return '/'.join(['bots', str(instance.id), 'bot_zip'])


class Bot(models.Model):
    RACES = (
        ('T', 'Terran'),
        ('Z', 'Zerg'),
        ('P', 'Protoss'),
        ('R', 'Random'),
    )
    TYPES = (
        ('cppwin32', 'cppwin32'),
        ('cpplinux', 'cpplinux'),
        ('dotnetcore', 'dotnetcore'),
        ('java', 'java'),
        ('nodejs', 'nodejs'),
        ('python', 'python'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)  # todo: change this to instead be an enrollment in a ladder?
    elo = models.SmallIntegerField(default=ELO_START_VALUE)
    bot_zip = PrivateFileField(upload_to=bot_zip_upload_to, max_file_size=1024 * 1024 * 50)  # max_file_size = 50MB
    bot_zip_md5hash = models.CharField(max_length=32, editable=False)
    plays_race = models.CharField(max_length=1, choices=RACES)
    type = models.CharField(max_length=32, choices=TYPES)

    def calc_bot_zip_md5hash(self):
        self.bot_zip_md5hash = calculate_md5(self.bot_zip.open(mode='rb'))

    # todo: once multiple ladders comes in, this will need to be updated to 1 bot race per ladder per user.
    def validate_one_bot_race_per_user(self):
        if Bot.objects.filter(user=self.user, plays_race=self.plays_race).exists() and not self.pk:
            raise ValidationError(
                'A bot playing that race already exists for this user. '
                'Each user can only have 1 bot per race.')

    def save(self, *args, **kwargs):
        self.calc_bot_zip_md5hash()
        super(Bot, self).save(*args, **kwargs)

    def clean(self):
        self.validate_one_bot_race_per_user()

    def __str__(self):
        return self.name

    @staticmethod
    def random_active():
        # todo: apparently this is really slow
        # https://stackoverflow.com/questions/962619/how-to-pull-a-random-record-using-djangos-orm#answer-962672
        return Bot.objects.filter(active=True).order_by('?').first()

    @staticmethod
    def active_count():
        return Bot.objects.filter(active=True).count()

    def random_active_excluding_self(self):
        if Bot.active_count() <= 1:
            raise RuntimeError("I am the only bot.")
        return Bot.objects.filter(active=True).exclude(id=self.id).order_by('?').first()

    def get_absolute_url(self):
        return reverse('bot', kwargs={'pk': self.pk})

    def as_html_link(self):
        return '<a href="{0}">{1}</a>'.format(self.get_absolute_url(), self.__str__())


_UNSAVED_FILEFIELD = 'unsaved__filefield'

# The following methods will temporarily store the bot_zip file  while we wait for the Bot model to be saved
# in order to generate an ID, which can then be used in the bot_zip file name
@receiver(pre_save, sender=Bot)
def skip_saving_bot_zip_file(sender, instance, **kwargs):
    if not instance.pk and not hasattr(instance, _UNSAVED_FILEFIELD):
        setattr(instance, _UNSAVED_FILEFIELD, instance.bot_zip)
        instance.bot_zip = None


@receiver(post_save, sender=Bot)
def save_bot_zip_file(sender, instance, created, **kwargs):
    if created and hasattr(instance, _UNSAVED_FILEFIELD):
        instance.bot_zip = getattr(instance, _UNSAVED_FILEFIELD)
        instance.save()
        # delete the saved instance
        instance.__dict__.pop(_UNSAVED_FILEFIELD)


class Map(models.Model):
    name = models.CharField(max_length=50, unique=True)
    file = models.FileField(upload_to='maps')

    def __str__(self):
        return self.name

    @staticmethod
    def random():
        # todo: apparently this is really slow
        # https://stackoverflow.com/questions/962619/how-to-pull-a-random-record-using-djangos-orm#answer-962672
        return Map.objects.order_by('?').first()


# todo: structure for separate ladder types
class Match(models.Model):
    map = models.ForeignKey(Map, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.id.__str__()


class Participant(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    participant_number = models.PositiveSmallIntegerField()
    bot = models.ForeignKey(Bot, on_delete=models.PROTECT, related_name='match_participations')
    resultant_elo = models.SmallIntegerField(null=True)

    def update_resultant_elo(self):
        self.resultant_elo = self.bot.elo
        self.save()

    def __str__(self):
        return self.bot.name


class Result(models.Model):
    TYPES = (
        ('InitializationError', 'InitializationError'),
        ('Timeout', 'Timeout'),
        ('ProcessingReplay', 'ProcessingReplay'),
        ('Player1Win', 'Player1Win'),
        ('Player1Crash', 'Player1Crash'),
        ('Player1TimeOut', 'Player1TimeOut'),
        ('Player2Win', 'Player2Win'),
        ('Player2Crash', 'Player2Crash'),
        ('Player2TimeOut', 'Player2TimeOut'),
        ('Tie', 'Tie'),
        ('Error', 'Error'),
    )
    match = models.OneToOneField(Match, on_delete=models.CASCADE, related_name='result')
    winner = models.ForeignKey(Bot, on_delete=models.PROTECT, related_name='matches_won', blank=True, null=True)
    type = models.CharField(max_length=32, choices=TYPES)
    created = models.DateTimeField(auto_now_add=True)
    replay_file = models.FileField(
        upload_to='replays')
    duration = models.IntegerField()

    def __str__(self):
        return self.created.__str__()

    def has_winner(self):
        return self.type in (
            'Player1Win',
            'Player1Crash',
            'Player1TimeOut',
            'Player2Win',
            'Player2Crash',
            'Player2TimeOut')

    def get_winner_loser_bots(self):
        bot1, bot2 = self.get_participant_bots()
        if self.type in ('Player1Win', 'Player2Crash', 'Player2TimeOut'):
            return bot1, bot2
        elif self.type in ('Player2Win', 'Player1Crash', 'Player1TimeOut'):
            return bot2, bot1
        else:
            raise Exception('There was no winner or loser for this match.')

    def get_participants(self):
        first = Participant.objects.filter(match=self.match, participant_number=1)
        second = Participant.objects.filter(match=self.match, participant_number=2)

        assert (first.count() == 1)
        assert (second.count() == 1)
        return first[0], second[0]

    def get_participant_bots(self):
        first, second = self.get_participants()
        return first.bot, second.bot

    # todo: validate that if the result type is either a timeout or tie, then there's no winner set etc
    # todo: use a model form

aiarena/core/views.py
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from private_storage.views import PrivateStorageDetailView

from aiarena.core.models import Bot, Result, User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class UserProfile(LoginRequiredMixin, UpdateView):
    form_class = UserProfileForm
    redirect_field_name = 'next'
    template_name = 'profile.html'
    success_message = "Profile saved successfully"

    def get_login_url(self):
        return reverse('login')

    def get_success_url(self):
        return reverse('profile')

    def get_object(self, *args, **kwargs):
        return self.request.user

    # todo: user bots
    # def get_context_data(self, **kwargs):
    #     context = super(UserProfile, self).get_context_data(**kwargs)
    #     # Add in the user's bots
    #     context['bot_list'] = self.request.user.bots
    #     return context


class BotUpload(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    redirect_field_name = 'next'
    template_name = 'botupload.html'
    success_message = "Bot was uploaded successfully"

    model = Bot
    fields = ['name', 'bot_zip', 'plays_race', 'type']

    def get_login_url(self):
        return reverse('login')

    def get_success_url(self):
        return reverse('botupload')

    def get_form_kwargs(self):
        # set the bot's user
        kwargs = super(BotUpload, self).get_form_kwargs()
        if kwargs['instance'] is None:
            kwargs['instance'] = Bot()
        kwargs['instance'].user = self.request.user
        return kwargs


class BotList(ListView):
    queryset = Bot.objects.filter(active=1).order_by('name')
    template_name = 'bots.html'


class BotDetail(DetailView):
    model = Bot
    template_name = 'bot.html'

    def get_context_data(self, **kwargs):
        context = super(BotDetail, self).get_context_data(**kwargs)

        results = Result.objects.filter(match__participant__bot=self.object).order_by('-created')[:10]

        # retrieve the opponent
        for result in results:
            result.opponent = result.match.participant_set.exclude(bot=self.object)[0]

        context['result_list'] = results
        return context


class AuthorList(ListView):
    queryset = User.objects.all().order_by('username').filter(is_active=1, serviceaccount=0)
    template_name = 'authors.html'


class AuthorDetail(ListView):
    # Even though this is an Author view, we can treat it as a Bot ListView because the logged in user's details
    # are already present in the template context by default
    model = Bot
    template_name = 'author.html'

    def get_queryset(self):
        return Bot.objects.filter(user=self.request.user).order_by('-created')


# Using a ListView, which has automated behaviour for displaying a list of models
class Ranking(ListView):
    # If we wanted all the bots, we could just set this and, because we're extending a ListView, it would
    # understand to get all the Bots, which could be referenced as "bot_list" in the template.
    # model = Bot

    # Instead, because we want to filter the bots, we define queryset,
    # which is also referenced as "bot_list" in the template.
    queryset = Bot.objects.filter(active=1).order_by('-elo')

    # If we didn't set this, the ListView would default to searching for a template at <module>/<modelname>_list.html
    # In this case, that would be "core/bot_list.html"
    template_name = 'ranking.html'

    # Old code for reference.
    # def get(self, request):
    #     bot_ranking = Bot.objects.filter(active=1).order_by('-elo')
    #     context = {'bot_ranking': bot_ranking}
    #     return render(request, 'ranking.html', context)


# Using a View - pretty bare-bones
class Results(View):
    def get(self, request):
        results = Result.objects.all().order_by('-created')[:100]
        for result in results:
            result.bot1 = result.match.participant_set.filter(participant_number=1)[0]
            result.bot2 = result.match.participant_set.filter(participant_number=2)[0]
        context = {'result_list': results}
        return render(request, 'results.html', context)


class BotZipDownloadView(PrivateStorageDetailView):
    model = Bot
    model_file_field = 'bot_zip'

    content_disposition = 'inner'

    def get_content_disposition_filename(self, private_file):
        return '{0}.zip'.format(private_file.parent_object.name)

    def can_access_file(self, private_file):
        user = private_file.request.user
        # Only allow staff or the owner of the file
        # temp hack to get arena clients working again.
        return True # user.is_authenticated and user.is_staff or private_file.parent_object.user == user

aiarena/templates/author.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<table id="author_table" style="width: 50%">
    <tr>
    {% load avatar_tags %}
        <th rowspan="3">{% avatar user.id 150 %}</th>
        <th colspan="2"><h2>{{ user.username }}</h2></th>
    </tr>
    <tr>
        <td><b>Joined</b></td>
        <td>{{ user.date_joined|date:"d. N Y" }}</td>
    </tr>
    <tr>
        <td><b>Last login</b></td>
        <td>{{ user.last_login|date:"d. N Y" }}</td>
    </tr>
</table>

<br>

<h2>Bots</h2>
<table id="bot_table" style="width: 50%">
    <tr>
        <td><b>Name</b></td>
        <td><b>Elo</b></td>
        <td><b>Type</b></td>
    </tr>
    {% for bot in bot_list %}
    <tr>
        <td><a href="/bots/{{ bot.id }}">{{ bot.name }}</a></td>
        <td>{{ bot.elo }}</td>
        <td>{{ bot.type }}</td>
    </tr>
    {% endfor %}

</table>

{% endblock %}

aiarena/templates/authors.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <table width="900" id="authorsTable">
        <tbody>
        {% load avatar_tags %}

            {% for author in user_list %}
                <tr>
                    <td>
                        <center>{% avatar author.id 150 %}</center>
                        <center><a href="/authors/{{ author.id }}">{{ author.username }}</a></center>
                        <br>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

aiarena/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static "style.css" %}">
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
    <title>{% block title %}AI Arena{% endblock %}</title>
</head>

<body>
<div id="page">
    <div id="sidebar">
        {% block sidebar %}
            <ul id="sidebar-items">
                <li>
                    <h3>pages</h3>
                    <ul class="links">
                        <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'rules' %}">{% trans "Rules" %}</a></li>
                        <li><a href="{% url 'authors' %}">{% trans "Authors" %}</a></li>
                        <li><a href="{% url 'bots' %}">{% trans "Bots" %}</a></li>
                        <li><a href="{% url 'ranking' %}">{% trans "Ranking" %}</a></li>
                        <li><a href="{% url 'results' %}">{% trans "Results" %}</a></li>
                    </ul>
                </li>

                <li>
                    <h3>user</h3>
                    <ul class="links">
                        {% if user.is_authenticated %}
                            <li>{% trans "Logged in" %}: {{ user.username }}</li>
                            <li><a href="{% url 'profile' %}">{% trans "Profile" %}</a></li>
                            <li><a href="{% url 'botupload' %}">{% trans "Bot upload" %}</a></li>
                            <li><a href="{% url 'password_change' %}">{% trans "Change password" %}</a></li>
                            <li><a href="{% url 'logout' %}">{% trans "Log out" %}</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}">{% trans "Login/Register" %}</a></li>
                        {% endif %}
                    </ul>
                </li>

                {% if user.is_staff %}
                <li>
                    <h3>admin</h3>
                    <ul class="links">
                            <li><a href="{% url 'admin:index' %}">{% trans "Admin" %}</a></li>
                            <li><a href="{% url 'api-root' %}">{% trans "API" %}</a></li>
                            <li><a href="https://logs.m1nd.io/app/infra#/logs?_g=()&logFilter=(expression:%27log.file.path%20:%20%22%2Fhome%2Faiarena%2Faiarena-client%2Faiarena-client.log%22%27,kind:kuery)&logMinimap=(intervalSize:3600000)&logPosition=(position:(tiebreaker:2510997,time:1557224559463),streamLive:!t)&logTextview=(textScale:small,wrap:!t)">{% trans "ClientLogs" %}</a></li>
                            <li><a href="https://m1nd.io:8006/">{% trans "Cluster" %}</a></li>
                    </ul>
                </li>
                {% endif %}

                <li>
                    <h3>stats</h3>
                    <ul class="links">
                        <li>Date: {% now "d. N Y" %}</li>
                        <li>Time: {% now "H:i:s" %} UTC</li>
                        <li>Matches (1h): {{ match_count_1h }}</li>
                        <li>Matches (24h): {{ match_count_24h }}</li>
                        <li>Active Bots: {{ active_bots }}</li>
                    </ul>
                </li>

                <li>
                    <h3>links</h3>
                    <ul class="links">
                        <li><a href="https://discord.gg/yDBzbtC">Discord</a></li>
                        <li><a href="https://gitlab.com/aiarena">GitLab</a></li>
                        <li><a href="https://trello.com/b/qw4DYU9H/ai-arena-website">Trello</a></li>
                        <li><a href="https://www.twitch.tv/aiarenastream">Twitch</a></li>
                    </ul>
                </li>
            </ul>
        {% endblock %}
    </div>

    <div id="header">
        {% block header %}
            <h1 class="site-title">StarCraft II AI Arena</h1>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        {% endblock %}
    </div>
</div>
</body>

</html>

aiarena/templates/bot.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h2 align="center"><b>{{ bot.name }}</b></h2>
    <table id="bot_table" style="width: 100%">
        <tbody>
        <tr>
            <td style="width: 30%;">
                <table id="bot_details" style="width: 100%; padding: 0em 1em 1em 2em;">
                    <tbody>
                    <tr>
                        <td><h3><b><u>Details</u></b></h3></td>
                    </tr>
                    <tr>
                        <td><h3>Author</h3> <a href="/authors/{{ bot.user.id }}/">{{ bot.user.username }}</a></td>
                    </tr>
                    <tr>
                        <td><h3>Race</h3> {{ bot.get_plays_race_display }}</td>
                    </tr>
                    <tr>
                        <td><h3>Type</h3> {{ bot.type }}</td>
                    </tr>
                    <tr>
                        <td><h3>ELO</h3> {{ bot.elo }}</td>
                    </tr>
                    </tbody>
                </table>
            </td>
            <td style="width: 70%; vertical-align: top">
                <table id="bot_results" style="width: 100%; vertical-align: top">
                    <tbody>
                    <tr>
                        <td><h3><b><u>Recent results</u></b></h3></td>
                    </tr>
                    <tr>
                        <td><b>Date</b></td>
                        <td><b>Opponent</b></td>
                        <td><b>Result</b></td>
                        <td><b>Duration</b></td>
                        <td><b>Replay</b></td>
                    </tr>
                    {% for result in result_list %}
                        <tr>
                            <td>{{ result.created|date:"d. N Y - H:i:s" }}</td>
                            <td>{{ result.opponent.bot.as_html_link |safe }}</td>
                            <td>{{ result.type }}</td>
                            <td>{{ result.duration }}</td>
                            <td><a href="{{ result.replay_file.url }}">Download</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>

{% endblock %}

aiarena/templates/bots.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <table width="900" id="botsTable">
        <tbody>
        <tr>
            <td><b>Name</b></td>
            <td><b>Author</b></td>
            <td><b>Race</b></td>
            <td><b>Type</b></td>
            <td><b>ELO</b></td>
        </tr>
        {% for bot in bot_list %}
            <tr>
                <td>{{ bot.as_html_link |safe }}</td>
                <td>{{ bot.user.username }}</td>
                <td>{{ bot.get_plays_race_display }}</td>
                <td>{{ bot.type }}</td>
                <td>{{ bot.elo }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

aiarena/templates/botupload.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <form method="post" action="{% url "botupload" %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="{% trans 'Upload' %}"/>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </form>
{% endblock %}

aiarena/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <ol>
        <h2>Under Construction</h2>
        <b>This website is currently under construction. Please feel free to have a look around, but be aware that things are likely to break currently.</b>
        <h3>Welcome to the Ai-Arena Open Beta!</h3>
        <b>Open Beta?</b><br>
        The Open Beta is all about breaking things, finding Bugs and enhancing the Workflow.<br>
        Everyone is invited to upload a Bot to the Ladder :)<br>
        <br>
        <br>
        <b>Instructions:</b><br>
        <li><a href="{% url 'registration_register' %}">{% trans "Register" %}</a></li>
        <li>Read the <a href="{% url 'rules' %}">Rules</a></li>
        <li>Upload your Bot to the Website and activate it</li>
        <br>
        Your Bot will be added to the Pool and starts fighting other Bots on the Ladder.
    </ol>
{% endblock %}

aiarena/templates/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <table>
        <tr>
            <td>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <input type=submit value="submit"/>
                </form>
            </td>
        </tr>
    </table>
{% endblock %}

aiarena/templates/ranking.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <table width="900" id="resultsTable">
        <tbody>
        <tr>
            <td><b>ELO</b></td>
            <td><b>Name</b></td>
            <td><b>Race</b></td>
            <td><b>Author</b></td>
            <td><b>Type</b></td>
        </tr>
        {% for bot in bot_list %}
            <tr>
                <td>{{ bot.elo }}</td>
                <td>{{ bot.as_html_link |safe }}</td>
                <td>{{ bot.get_plays_race_display }}</td>
                <td>{{ bot.user.username }}</td>
                <td>{{ bot.type }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

aiarena/templates/results.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <table width="900">
        <tbody>
        <tr>
            <td><b>Date</b></td>
            <td><b>Bot 1</b></td>
            <td><b>Bot 2</b></td>
            <td><b>Result</b></td>
            <td><b>Duration</b></td>
            <td><b>Replay</b></td>
        </tr>
        {% for result in result_list %}
            <tr>
                <td>{{ result.created|date:"d. N Y - H:i:s" }}</td>

                {% if result.winner == result.bot1.bot %}
                        <td><b>{{ result.bot1.bot.as_html_link |safe }}</b></td>
                        <td>{{ result.bot2.bot.as_html_link |safe }}</td>
                {% elif result.winner == result.bot2.bot %}
                        <td>{{ result.bot1.bot.as_html_link |safe }}</td>
                        <td><b>{{ result.bot2.bot.as_html_link |safe }}</b></td>
                {% else %}
                        <td>{{ result.bot1.bot.as_html_link |safe }}</td>
                        <td>{{ result.bot2.bot.as_html_link |safe }}</td>
                {% endif %}

                <td>{{ result.type }}</td>
                <td>{{ result.duration }}</td>
                <td><a href="{{ result.replay_file.url }}">Download</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

aiarena/templates/rules.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h3>General Rules</h3>
    Bot authors must ensure that their creations are not harming the ladder system in any way, including but not limited to:<br><br>
    <li>Slowing down the system on purpose</li>
    <li>Generating huge amounts of data on the disc without purpose</li>
    <li>Tempering with the filesystem or memory</li>
    <li>Network access of any kind besides connecting to the local sc2api process is strictly forbidden</li>
    <li>Uploading copies (clones) of another bot is forbidden</li>

    <h3>Bot Development</h3>
    The Ladder supports multiple programming languages<br>
    To make sure the bot works on the ladder you must follow the following standards:<br>

    <br>
    <b>Python:</b>
    <li>Version: Python 3.7</li>
    <li>Python Modules: sc2, pysc2, numpy, tensorflow (cpu), scipy</li>
    <li>Bot called via run.py</li>
    Website: <a href="https://github.com/Dentosal/python-sc2">python-sc2</a><br>

    <br>
    <b>C++:</b>
    <li>Can be compiled on Windows or Linux</li>
    <li>Windows: Bot called via botname.exe</li>
    <li>Linux: Bot called via botname</li>
    Website: <a href="https://github.com/Blizzard/s2client-api">s2client-api</a><br>

    <br>
    <b>Java:</b>
    <li>Version: Java 11</li>
    <li>Bot called via botname.jar</li>
    Website: <a href="https://ocraft.github.io/ocraft-s2client/">ocraft-s2client</a><br>

    <br>
    <b>DotNetCore:</b>
    <li>Version: DotNetCore 2.2</li>
    <li>Bot called via botname.dll</li>
    Website: <a href="https://github.com/NikEyX/SC2-CSharpe-Starterkit">SC2-CSharpe-Starterkit</a><br>

    <br>
    <b>GoLang:</b>
    <li>Bot called via botname</li>
    Website: <a href="https://github.com/chippydip/go-sc2ai">go-sc2ai</a><br>

    <br>
    <b>NodeJS:</b>
    <li>Bot called via botname.js</li>
    Website: <a href="https://github.com/node-sc2/core">node-sc2/core</a><br>

    <br>
    For a successful upload the Bot must be packed using zip. (Max 25 MB)<br>
    Please make sure the executable is in root path after extraction (Don't zip the directory)<br>
    <br>
    The bots may write to a data directory, the data can be downloaded via profile page.
    <br>
    <br>

    <h3>Maps</h3>
    Download the latest ladder pack from the <a href="https://github.com/Blizzard/s2client-proto#downloads">GitHub</a> Repository.

    <h3>Security</h3>
    The Ladder is completely automated and in theory attacks are quite simple to achieve. To counter this the games are
    played on seperated LadderServers which are firewalled and reset themselves after every game.
    <br>
    Network access is denied and will lead to a permanent ban from the ladder.
    <br>
    The training data is stored on another server and will be fetched before each game.

    <h3>Match Queue</h3>
    The match queue makes sure all Bots have to play against every other bot on the ladder.
    If the queue is empty a fresh one is generated containing all active bots. (Round-Robin)
{% endblock %}